language: python
git:
  depth: 5
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    python: '2.7'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.4'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.5'
script:
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import brent_search; brent_search.test()"
- popd
branches:
  only:
  - master
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  on:
    distributions: sdist bdist_wheel
    repo: glimix/brent-search
