language: python
sudo: false
python: 3.6
env:
  - PKG_NAME=brent_search
addons:
  apt:
    packages:
    - pandoc
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: dK4R4QcMiRG9B5/C2QcoY5oD7fqfYg9G+/lCcFh51O2M8SihAsur80uvD/d07DQifqpkWTpTjsFE9horlmlONkIh1QhIYnCqqaKta1VVUHOMyTNWaZxht3nKT4jp4cBtmDVr3d7ZyuPfKXWSQhaPVJGAYvsrxLD8yba3rERK2PE84RpuWdVr4g4XKmUpO6uyEGAY9yFuY8/zpcmCy9Df+9amhWa1qXVh2NeZxzBb2lr742jZF+CdyiZVfun1dkGgD7/fuj/gc2/u/MRwcvoTAxyjCCTqOfcm4jwNe3JRHA2zi2YR2MNOzc+Ey1OiyrSUv9YolZSrWiD2K5DVEBgBU4SqfHnWacElUJ79hlCV0q5zSwWWC0Mi9C76/A2YcYt63US2qKq62fHc6F2skkSINswQCCJ7dgeUAgXlXT8khzMOAEB3cRXxuTSkDLGZPUa/bqktc36gQt462IGnunYl+srjY1UfdxGi8mlm/kupJY5IgCi6e5jxrQSNzrSal3uuNGtl35DmcndqNVfI6qGClHSbY5rKPp6of6oW39rXZANxWuz5QRFHZYN2cheeT/G3SPIX41SyAjkPsutJnamLmsDG4J52HRUuGDkDHbW8V1sKWHBs43EuEa4zOrb7Exa49ZV7JhW5OtWrAx8695fbDpyPRcQJXXydCTWwtlMvyto=
  on:
    tags: true
    repo: limix/brent-search
    branch: master
