language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.5'
script:
- pip install pypandoc
- python -c "from pypandoc import download_pandoc as dp; dp(targetfolder='~/bin/');"
- export PATH=~/bin:$PATH
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import brent_search; brent_search.test()"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: EXTDXz3TYRprUe8FI12YC/kiZAIxsqQr3QStsoSmhbdp4LAn+tUFtNnUH3C5PylQHBlQi14K6NTfVF2MXGHJ/kMQLuwVSYARucn5cXWgQ88mEee12PH95qc4rqbCL5K2i79TTUH6Nf3ddC7BnRtxfTTJPSMbMv/xtGDV1jXmo+lmJXLzyxz+ZQ24Wj1LmvnLphExrXVcdsaJul680htdYXmCjgXLZ0nIn3wTDuB3YQpt/QItamE1ObqYUSxEGdKkFYdW8/bT+M7LB/XwBY3ezJNz6On7gQo0rOwqL5oXQir7MpSZee20OS5Q3hkyWsUtPwib7NQiocmInLwiZcXq/jxWM17HxV0dCj9brPtxv3iS3+rF4/HSRtcrcQ/SwYq9AYbpps09ecx1k57MoEXw5xhSIqYg9BHPRGwCTHcDg9QRZrpfTDPLvwDTDF46em1uLJuzomkclKQfttzp9/U2IBZ789PTVgcXBcqo6lUt7lHMhB8gg7kMf4xgdTJgzokVfbK9yRT93GbOQTUB39JaXBzwHbHBeqqRx6Msc1qCie5SvOja5H7II3j4SRD6yjVi7MLjnn+AVEbqdK6AuZqlbIEAFZ3YGdN82JDWsCi8KVePIYQW6brr4P3xZJCEmfJoUsywCfkgDXP23iH9MQh6EQe3wRD2ME0BIMCKTsxudGs=
  on:
    distributions: sdist bdist_wheel
    repo: glimix/brent-search
